# This code was written with the support of ChatGPT.

import sys

def count_lines(filename, keyword = None): # count_lines function definition
    try:
        with open(filename, "r", encoding="utf-8") as file:
            lines = file.readlines() # Reading all lines to the variable 'lines'
            if keyword:
                lines = [line for line in lines if keyword.lower() in line.lower()] # Phrase searching, filtering, modifying variable 'lines'; generated by ChatGPT:
            return sum(1 for _ in lines) # returning number of lines; generated by ChatGPT
    except FileNotFoundError: # Error handling; generated by ChatGPT
        print(f"File '{filename}' does not exist!")
        sys.exit(1)

if __name__ == "__main__": # Entry point
    if len(sys.argv) < 2:
        print("Usage: python Count_lines.py <file_path> [phrase]")
    else:
        filename = sys.argv[1]
        keyword = sys.argv[2] if len(sys.argv) > 2 else None
        if keyword:
            print(f"Number of lines in file with phrase '{keyword}':", count_lines(filename, keyword))
        else:
            print("Number of lines in file:", count_lines(filename))

